; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SteamlessController"
#define MyAppVersion "1.0"
#define MyAppPublisher "SteamlessController contributors"
#define MyAppURL "https://github.com/david419kr/steamless-controller-dualshock4"
#define MyAppExeName "SteamlessController.exe"
#ifndef MyBuildDir
#define MyBuildDir "..\build\release\Release"
#endif
#ifndef PrereqDir
#define PrereqDir "..\build\prereqs"
#endif
#ifndef InstallerOutputDir
#define InstallerOutputDir "..\build\installer"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4E6FF864-969A-44C6-B4AC-848F22D5EF57}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputBaseFilename=SteamlessController-Setup
OutputDir={#InstallerOutputDir}
SetupIconFile=SteamControllerON.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "install_hidhide"; Description: "Install HidHide for Steam duplicate-input prevention (recommended)"; GroupDescription: "Optional components:"

[Files]
Source: "{#PrereqDir}\VC_redist.x64.exe"; DestName: "VC_redist.x64.exe"; Flags: dontcopy noencryption
Source: "{#PrereqDir}\USBip-x64.exe"; DestName: "USBip-x64.exe"; Flags: dontcopy noencryption
Source: "{#PrereqDir}\HidHide-x64.exe"; DestName: "HidHide-x64.exe"; Flags: dontcopy noencryption
Source: "{#MyBuildDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyBuildDir}\viiper.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyBuildDir}\VIIPER-LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#MyBuildDir}\VIIPER-SOURCE.txt"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#MyBuildDir}\viiper-v0.6.1-ds4-compat.patch"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#MyBuildDir}\viiper-v0.6.1-dualsense.patch"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#MyBuildDir}\viiper-v0.6.1-ns2pro-core.patch"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#MyBuildDir}\ns2pro-overlay\*"; DestDir: "{app}\ns2pro-overlay"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; Check: ShouldOfferLaunch

[Code]
var
  PrereqNeedsRestart: Boolean;

function IsVcRuntimeInstalled(): Boolean;
var
  Installed: Cardinal;
begin
  Result := RegQueryDWordValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Installed', Installed) and
            (Installed = 1);
end;

function IsUsbIpInstalled(): Boolean;
begin
  Result := FileExists(ExpandConstant('{commonpf}\USBip\usbip.exe')) or
            FileExists(ExpandConstant('{commonpf}\USBip\usbipd.exe'));
end;

function IsHidHideInstalled(): Boolean;
begin
  Result :=
    FileExists('C:\Program Files\Nefarius Software Solutions\HidHide\x64\HidHideCLI.exe') or
    FileExists('C:\Program Files\Nefarius Software Solutions\HidHide\HidHideCLI.exe') or
    FileExists('C:\Program Files\Nefarius Software Solutions e.U\HidHide\x64\HidHideCLI.exe') or
    FileExists('C:\Program Files\Nefarius Software Solutions e.U\HidHide\HidHideCLI.exe');
end;

function IsSuccessOrRestartCode(ResultCode: Integer): Boolean;
begin
  Result := (ResultCode = 0) or
            (ResultCode = 3010) or
            (ResultCode = 1641) or
            (ResultCode = 1638);
end;

function RunPrereq(FileName, Params, DisplayName: String): Boolean;
var
  ResultCode: Integer;
  InstallerPath: String;
begin
  Result := False;
  Log('Installing prerequisite: ' + DisplayName);
  ExtractTemporaryFile(FileName);
  InstallerPath := ExpandConstant('{tmp}\' + FileName);

  if not Exec(InstallerPath, Params, '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
  begin
    MsgBox('Failed to start ' + DisplayName + ' installer.', mbError, MB_OK);
    Exit;
  end;

  if not IsSuccessOrRestartCode(ResultCode) then
  begin
    MsgBox(DisplayName + ' installer failed with exit code ' + IntToStr(ResultCode) + '.', mbError, MB_OK);
    Exit;
  end;

  if (ResultCode = 3010) or (ResultCode = 1641) then
    PrereqNeedsRestart := True;

  Result := True;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  PrereqNeedsRestart := False;

  if not IsVcRuntimeInstalled() then
  begin
    if not RunPrereq('VC_redist.x64.exe', '/install /quiet /norestart', 'Microsoft Visual C++ Redistributable 2015-2022 x64') then
    begin
      Result := 'Microsoft Visual C++ Redistributable installation failed.';
      Exit;
    end;
  end;

  if not IsUsbIpInstalled() then
  begin
    if not RunPrereq('USBip-x64.exe', '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', 'usbip-win2') then
    begin
      Result := 'usbip-win2 installation failed.';
      Exit;
    end;
  end;

  if WizardIsTaskSelected('install_hidhide') and not IsHidHideInstalled() then
  begin
    if not RunPrereq('HidHide-x64.exe', '/exenoui /qn REBOOT=ReallySuppress', 'HidHide') then
    begin
      Result := 'HidHide installation failed.';
      Exit;
    end;
  end;

  NeedsRestart := PrereqNeedsRestart;
end;

function ShouldOfferLaunch(): Boolean;
begin
  Result := not PrereqNeedsRestart;
end;

